### ISSUE TITLE
API URL's

### ISSUE THREAD

**Issue by mark-jones-rga** [MatthewJohn/terrareg#3]
Hi,
  I am unable to find the API URL's for creating namespaces and the like.  Can you point me in the right direciton?

**Comment by mark-jones-rga** [comment]
Nevermind I found them!

**Comment by MatthewJohn** [comment]
> Nevermind I found them!

Hi Mark - sorry about this.

I will create a ticket to document them more thoroughly - I was playing with integrating the APIs with swagger a couple of days ago (managed to get a test working with 1, but wasn't going to be an incredibly easy change - https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/308).. but was considering writing a small script to write the details of them to a markdown file.

I'll create a separate ticket for this and prioritise :)

**Comment by MatthewJohn** [comment]
I've created https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/354

**Comment by MatthewJohn** [comment]
I've added a basic script to generate documentation based on the current docstrings (https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/312)

The docs are available here: https://github.com/MatthewJohn/terrareg/blob/main/docs/API.md

Hope this helps :)

Many thanks

**Comment by mark-jones-rga** [comment]
Matt, No worries thanks.  We have been getting this setup in our environment and really appreciate the work so far!

**Comment by MatthewJohn** [comment]
> We have been getting this setup in our environment
That's wonderful :) If there's any issues or feature requests that you help, feel free to reach out :)

> but have to figure out our corporate policies first
I can imagine :laughing: 

And thank you - any/all contributions would be gladly welcome :)

On a long shot, if you do successfully deploy and get some benefits from it, if there's a possibility, if would be wonderful to add your organisation to the README as "users" of it (but completely understand if you/they don't want to :) )

**Comment by mark-jones-rga** [comment]
I am not sure on adding to README with corp policies, but we are trying to get approved soon from the legal dept!

**Comment by MatthewJohn** [comment]
> I am not sure on adding to README with corp policies

Totally understand :)

> FYI we have tested a working OIDC implementation with Okta, but had to add 'groups' to scope.

This is interesting! I am/was using Okta whilst implementing this feature. I've just doubled checked authenticating via OIDC and Terrareg _is_ able to obtain a list of groups from Okta. I assume this is related to a difference in configurations on Okta.
Happy to share my configuration somehow to compare to determine if I've used an abnormal configuration

> We also have an LB in front and had to add insecure oauth env for the docker image to work properly. One of my colleagues is working on some modifications to that to open a PR for review.

Fantastic - thank you :)

**Comment by mark-jones-rga** [comment]
Sounds good, thanks!  What we found was that without adding 'scope' we were able to login regardless of whether groups has been configured in the user-groups or not.  So, anyone in the SSO application on Okta was able to get in.  Adding scopes restricted this, but we will do some more testing and let you know.

I'll shoot you an email so we can chat there out of the "issues"

PS I am an infrastructure guy by trade and not so much a developer.  So, excuse any "dumb" questions lol.

**Comment by MatthewJohn** [comment]
> What we found was that without adding 'scope' we were able to login regardless of whether groups has been configured in the user-groups or not.
This is actually by-design. In terms of Okta (and other SAML/OIDC providers), once assigned the user is able to authenticate, they can login regardless of the user group configuration.
However, once [ENABLE_ACCESS_CONTROLS](https://github.com/MatthewJohn/terrareg/blob/main/docs/CONFIG.md#enable_access_controls) is enabled, although the user can _still_ login, they will have no more permissions than a non-authenticated user. At which point, user-groups can be configured and if a user is part of a matching group, they will be given the privileges (per-namespace WRITE/ADMIN or global superuser).

Since we don't have any functionality that blocks access to any "read" APIs (meaning anyone can freely browse the site), whether a user could login or not didn't seem to make much difference (unless ENABLE_ACCESS_CONTROLS is false, at which point any logged in user has full superuser privileges). Hopefully this captures the above: https://github.com/MatthewJohn/terrareg/blob/main/docs/USER_GUIDE.md#access-controls, though let me know if it's unclear (I'm sure all documentation is best viewed in the eyes of the writer ;) )

> I'll shoot you an email so we can chat there out of the "issues"
Absolutely :)

> PS I am an infrastructure guy by trade and not so much a developer. So, excuse any "dumb" questions lol.
haha don't worry - my profession is also system engineering/devops ;)
