### ISSUE TITLE
Feature req: Specify modules / namespaces as code

### ISSUE THREAD

**Issue by bmaximuml** [MatthewJohn/terrareg#35]
I have terrareg deployed in multiplie environments. It would be nice to be able to specify modules and namespaces to create (if they don't exist) in a configuration file (JSON/YAML maybe?) which I could then load in. This owuld allow me to define the modules in one place and then easily copy them between environments. It also effectively self documents which modules are present, and how to add new ones

**Comment by MatthewJohn** [comment]
Hey @bmaximuml 

Is this purely namespaces and modules? (as opposed to module versions?)

If so, as part of #32 , I created a Terraform provider for Terrareg (https://registry.terraform.io/providers/dockstudios/terrareg and https://github.com/DockStudios/terraform-provider-terrareg) - I'm not sure if this would solve your use-case (though Terraform would need running, rather than dynamically loading them from a config file on startup)

Thanks
Matt

**Comment by bmaximuml** [comment]
Oh wow this is even better than what I had in mind!
I'll try this out today

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/509
gitlab-issue-id:509
