### ISSUE TITLE
Use PAT token for Git based hosting

### ISSUE THREAD

**Issue by aca8089** [MatthewJohn/terrareg#57]
For git based hosting how can we use PAT tokens instead of SSH key.

@MatthewJohn Can you please help with this

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/535
gitlab-issue-id:535

**Comment by aca8089** [comment]
Also does this support Azure Repos ?

**Comment by MatthewJohn** [comment]
Hey @aca8089, From Terrareg's point of view, it will take any git URL, the only requirements are:
 * It can clone it when a version is indexed using the SSH key provided to it
 * Terraform will know what to do with it

With regards to PAT tokens, is this about using PAT tokens instead of SSH keys for Terrareg or the users of the modules?
If it's the users, I would assume the best way would be to use a Git credential helper.

With regards to Terrareg, if you'd want to use PAT tokens for indexing, would these be assigned per-repository or globally across the instance?

With regards to Azure (since I haven't used it before), does it do anything special with authentication (does SSH key access work?) - unless it does do something special, I see no reason why it wouldn't work.

**Comment by aca8089** [comment]
Hi @MatthewJohn  Thanks for the reply.

Actually I was trying to use the git based hosting in terrareg but instead of adding SSH keys in the GitHub/Azure repository, I was thinking to use access tokens which is the recommended way.

**Comment by MatthewJohn** [comment]
I've had a quick go at implementing this this morning: https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/413
It basically allows authentication for http(s) repositories via a globally set username/password.
Hope this fixes the use-case

Many thanks
MAtt

**Comment by aca8089** [comment]
@MatthewJohn Thanks for the changes.

Are we planning for merging the code soon ?

**Comment by MatthewJohn** [comment]
> @MatthewJohn Thanks for the changes.
> 
> Are we planning for merging the code soon ?

Hey,

Yep, I'm just pleading with tests :)

**Comment by MatthewJohn** [comment]
This is now released in 3.10.0 :)
